artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url:https://github.com/Tejaswini-Gururaju/Complete-ML-Project-with-ML-Flow/raw/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


